select top 1000
	PRODUCT.PROD_CD_9, 
	SIZE.SIZE_DIM_1_DESC,
	SIZE.SIZE_DIM_2_DESC,
	PROD_SAP_MORE.DMD_ATTR_DESC, 
	PRODUCT.PROD_CAT_CD,
	CONSUMER_GRP.CONSM_GRP_LONG_DESC,
	BRAND.BRAND_SHORT_DESC,
	CALENDAR_DAY.FISC_MTH_KEY as SHIPPED_FMONTH,
	sum(ORD_ITEM_SIZE.ORD_SIZE_SHIP_QTY) as SHIPPED_QTY
	
from
	EDWARD.ORD_ITEM
	inner join EDWARD.ORD_ITEM_SIZE on
		(ORD_ITEM.ORD_SRCE_CD = ORD_ITEM_SIZE.ORD_SRCE_CD and ORD_ITEM.ORD_CNTL_NUM = ORD_ITEM_SIZE.ORD_CNTL_NUM and ORD_ITEM.ORD_ENTRY_DT = ORD_ITEM_SIZE.ORD_ENTRY_DT and ORD_ITEM.POSNR_SLS_DOC_ITEM_NUM = ORD_ITEM_SIZE.POSNR_SLS_DOC_ITEM_NUM)
	inner join EDWARD.ORDER_HEADER on
		(ORD_ITEM.ORD_SRCE_CD = ORDER_HEADER.ORD_SRCE_CD and ORD_ITEM.ORD_CNTL_NUM = ORDER_HEADER.ORD_CNTL_NUM and ORD_ITEM.ORD_ENTRY_DT = ORDER_HEADER.ORD_ENTRY_DT)

-- To Pull Demand Attribute Information
	left join EDWARD.PROD_SAP_MORE on
		(ORD_ITEM.PROD_KEY = PROD_SAP_MORE.PROD_KEY)

-- To Pull Item Size Information
	left join EDWARD.SIZE on
		(ORD_ITEM_SIZE.SIZE_DIM_1_CD = SIZE.SIZE_DIM_1_CD and ORD_ITEM_SIZE.SIZE_DIM_2_CD = SIZE.SIZE_DIM_2_CD)

-- To Pull Brand, Consumer Group, and Category Information
	left join EDWARD.PRODUCT on
		(ORD_ITEM.PROD_KEY = PRODUCT.PROD_KEY)
	inner join EDWARD.BRAND_EXT_BRAND_ASSO on
		(PRODUCT.BRAND_EXT_ID = BRAND_EXT_BRAND_ASSO.BRAND_EXT_ID)
	inner join EDWARD.BRAND on
		(BRAND_EXT_BRAND_ASSO.BRAND_ID = BRAND.BRAND_ID)
	inner join EDWARD.CONSUMER_GRP_EXT on
		(PRODUCT.CONSM_GRP_EXT_ID = CONSUMER_GRP_EXT.CONSM_GRP_EXT_ID)
	inner join EDWARD.CONSUMER_GRP on
		(CONSUMER_GRP_EXT.CONSM_GRP_ID = CONSUMER_GRP.CONSM_GRP_ID)

-- To Aggregate To Fiscal Month Level
	left join EDWARD.CALENDAR_DAY on	
		(ORDER_HEADER.ORD_ROG_DT = CALENDAR_DAY.CAL_DAY_KEY)

where
	CALENDAR_DAY.FISC_YR_KEY in (2016, 2017)
	
group by
	1, 2, 3, 4, 5, 6, 7, 8
