
select
		PRODUCT.PROD_CD_9, 
		SIZE.SIZE_DIM_1_DESC,
		SIZE.SIZE_DIM_2_DESC,
		SRCE_LOC.SRCE_LOC_NAME,
		SRCE_LOC.SRCE_LOC_ID,
		INVTY_RECON.SAP_SIZE_INVTY_DAILY.INVTY_ERDAT_DT,
		sum(INVTY_RECON.SAP_SIZE_INVTY_DAILY.PROD_SIZE_ONHAND_QTY) as ON_HAND_INV
		
from
		-- Foundation Table
		INVTY_RECON.SAP_SIZE_INVTY_DAILY
		
		-- To Pull Item Size Information
		left join EDWARD.SIZE on
		                (INVTY_RECON.SAP_SIZE_INVTY_DAILY.SIZE_DIM_1_CD = SIZE.SIZE_DIM_1_CD and INVTY_RECON.SAP_SIZE_INVTY_DAILY.SIZE_DIM_2_CD = SIZE.SIZE_DIM_2_CD)
		                
		-- To Pull Brand, Consumer Group, and Category Information
		left join EDWARD.PRODUCT on
		                (INVTY_RECON.SAP_SIZE_INVTY_DAILY.PROD_KEY = PRODUCT.PROD_KEY)
		inner join EDWARD.BRAND_EXT_BRAND_ASSO on
		                (PRODUCT.BRAND_EXT_ID = BRAND_EXT_BRAND_ASSO.BRAND_EXT_ID)
		inner join EDWARD.BRAND on
		                (BRAND_EXT_BRAND_ASSO.BRAND_ID = BRAND.BRAND_ID)
		inner join EDWARD.CONSUMER_GRP_EXT on
		                (PRODUCT.CONSM_GRP_EXT_ID = CONSUMER_GRP_EXT.CONSM_GRP_EXT_ID)
		inner join EDWARD.CONSUMER_GRP on
		                (CONSUMER_GRP_EXT.CONSM_GRP_ID = CONSUMER_GRP.CONSM_GRP_ID)
		
		-- To Pull CSC Names
		left join EDWARD.SRCE_LOC on (INVTY_RECON.SAP_SIZE_INVTY_DAILY.SRCE_LOC_ID = SRCE_LOC.SRCE_LOC_ID)
		
		-- To Aggregate To Fiscal Month Level
		left join EDWARD.CALENDAR_DAY on             
		                (INVTY_RECON.SAP_SIZE_INVTY_DAILY.INVTY_ERDAT_DT = CALENDAR_DAY.CAL_DAY_KEY)

where 
        CALENDAR_DAY.CAL_DAY_KEY = 1170202
        and BRAND.BRAND_ID like 'L'
        and CONSUMER_GRP.CONSM_GRP_ID like 'MEN'

group by
                1, 2, 3, 4, 5, 6
