
select
	BRAND.BRAND_SHORT_DESC,
	CONSUMER_GRP.CONSM_GRP_SHORT_DESC,
	PROD_SAP_MORE.DMD_ATTR_DESC,
	INVTY_RECON.SAP_SIZE_INVTY_DAILY.INVTY_ERDAT_DT,
	PRODUCT.PROD_CAT_CD,
	sum(INVTY_RECON.SAP_SIZE_INVTY_DAILY.PROD_SIZE_ONHAND_QTY) as ON_HAND_INV
	SRCE_LOC.SRCE_LOC_NAME,
	SRCE_LOC.SRCE_LOC_ID
from
	-- Foundation Table
	INVTY_RECON.SAP_SIZE_INVTY_DAILY
	
	-- To Pull Item Size Information
	left join EDWARD.SIZE on
        (INVTY_RECON.SAP_SIZE_INVTY_DAILY.SIZE_DIM_1_CD = SIZE.SIZE_DIM_1_CD and INVTY_RECON.SAP_SIZE_INVTY_DAILY.SIZE_DIM_2_CD = SIZE.SIZE_DIM_2_CD)
	                
	-- To Pull Brand, Consumer Group, and Category Information
	left join EDWARD.PROD_KEY on
        (INVTY_RECON.SAP_SIZE_INVTY_DAILY.PROD_KEY = PRODUCT.PROD_KEY)
	inner join EDWARD.BRAND_EXT_BRAND_ASSO on
        (PRODUCT.BRAND_EXT_ID = BRAND_EXT_BRAND_ASSO.BRAND_EXT_ID)
	inner join EDWARD.BRAND on
        (BRAND_EXT_BRAND_ASSO.BRAND_ID = BRAND.BRAND_ID)
	inner join EDWARD.CONSUMER_GRP_EXT on
        (PRODUCT.CONSM_GRP_EXT_ID = CONSUMER_GRP_EXT.CONSM_GRP_EXT_ID)
	inner join EDWARD.CONSUMER_GRP on
        (CONSUMER_GRP_EXT.CONSM_GRP_ID = CONSUMER_GRP.CONSM_GRP_ID)
    inner join EDWARD.PROD_SAP_MORE on
    	(PRODUCT.PROD_KEY = PROD_SAP_MORE.PROD_KEY)
	
	-- To Pull CSC Names
	left join EDWARD.SRCE_LOC on 
		(INVTY_RECON.SAP_SIZE_INVTY_DAILY.SRCE_LOC_ID = SRCE_LOC.SRCE_LOC_ID)
	
	-- To Aggregate To Fiscal Month Level
	left join EDWARD.CALENDAR_DAY on             
        (INVTY_RECON.SAP_SIZE_INVTY_DAILY.INVTY_ERDAT_DT = CALENDAR_DAY.CAL_DAY_KEY)

where 
    SAP_SIZE_INVTY_DAILY.INVTY_ERDAT_DT > 1121231       

group by
    1, 2, 3, 4, 5, 6

