SELECT 
--    CAST(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.SALESORG AS CHAR(10)) AS SalesOrg,
    PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.PLANT AS Plant,
    CAST(NULL AS CHAR(10)) AS Season,
    PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.MATERIAL AS PC9,
  /*  , CASE 
        WHEN POSITION('-' IN PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL) > 0 
            THEN SUBSTR(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL, 1, POSITION('-' IN PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL)  -1) || SUBSTR(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL, POSITION('-' IN PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL) + 1, CHARACTER_LENGTH(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL))
        ELSE PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL
      END AS Size, */
    fiscmnths.fiscmnth,
    PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_REQCAT AS Quality,
    CAST(0 AS DECIMAL(10,0)) AS BegInvQty,
    CAST(SUM(
        CASE 
/*            WHEN DOC_TYPE = 'ZCQ' AND COALESCE(CONTRACT_OPN_QTY ,0) <= 0 
                THEN 0 
            WHEN DOC_TYPE = 'ZCQ' AND COALESCE(CONTRACT_OPN_QTY ,0) > 0
                THEN COALESCE(CONTRACT_OPN_QTY ,0) */
	        WHEN COALESCE(CONF_QTYF, 0) - COALESCE(ZPGI_QTY, 0) - COALESCE(
                CASE
                    WHEN AF_REJCOD NOT IN ( ' ' , 'J0')
                        THEN BVTSORDQTY 
                    ELSE 0 
                END, 0) < 0 
                THEN 0
	        ELSE COALESCE(CONF_QTYF, 0) - COALESCE(ZPGI_QTY, 0) - COALESCE(
                CASE 
                    WHEN AF_REJCOD NOT IN ( ' ' , 'J0') 
                        THEN BVTSORDQTY 
                    ELSE 0 
                END, 0)
	        END) AS DECIMAL(10,0)) AS OpenOrdQty,
    CAST(0 AS DECIMAL(10,0)) AS DueInQty,
    CAST(0 AS DECIMAL(10,0)) AS ForecastQty
    
FROM 
    PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE

    INNER JOIN #ATS_Month_Calendar fiscmnths
        ON (PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.ZHREQ_DTE = fiscmnths.cal_day_key)

    , #start_date_vl1

WHERE
    PLANT IN ('1018', '3002', '3003', '3045')
    AND DOC_TYPE IN ('Z2ND','ZOR')
    AND MATERIAL like '00501-0101'
    AND AF_GRDVAL <> ' '

GROUP BY 
--    CAST(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.SALESORG AS CHAR(10)),
    PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.PLANT,
    PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.MATERIAL,
/*  CASE 
        WHEN POSITION('-' IN PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL) > 0 
            THEN SUBSTR(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL, 1, POSITION('-' IN PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL)  -1) || SUBSTR(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL, POSITION('-' IN PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL) + 1, CHARACTER_LENGTH(PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL))
        ELSE PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_GRDVAL
    END, */
    fiscmnths.fiscmnth
    , PROD_EDW_VIEWS.SV_OTC_ORDER_SIZE.AF_REQCAT

HAVING SUM(
	CASE 
/*        WHEN DOC_TYPE = 'ZCQ' AND COALESCE(CONTRACT_OPN_QTY ,0) <= 0 
            THEN 0 
	    WHEN DOC_TYPE = 'ZCQ' AND COALESCE(CONTRACT_OPN_QTY ,0) > 0
            THEN COALESCE(CONTRACT_OPN_QTY ,0) */
        WHEN COALESCE(CONF_QTYF, 0) - COALESCE(ZPGI_QTY, 0) - COALESCE(
            CASE
                WHEN AF_REJCOD NOT IN ( ' ' , 'J0') 
                    THEN BVTSORDQTY 
                ELSE 0
            END, 0) < 0 
            THEN 0
	    ELSE COALESCE(CONF_QTYF, 0) - COALESCE(ZPGI_QTY, 0) - COALESCE(CASE 
            WHEN AF_REJCOD NOT IN ( ' ' , 'J0') 
                THEN BVTSORDQTY 
            ELSE 0 
        END, 0)
	END) > 0
